package com.example.autohub.presentation.model

enum class StringResNamePresentation {

    // CarOptions

    LABEL_SEDAN,
    LABEL_COUPE,
    LABEL_CONVERTIBLE,
    LABEL_STATION_WAGON,
    LABEL_HATCHBACK,
    LABEL_VAN,
    LABEL_MINIVAN,
    LABEL_SUV,
    LABEL_CROSSOVER,
    LABEL_PICKUP_TRUCK,
    LABEL_LIMOUSINE,

    LABEL_NOT_BROKEN,
    LABEL_BROKEN,
    LABEL_NOT_WORKING,

    LABEL_MANUAL,
    LABEL_AUTOMATIC,
    LABEL_VARIATOR,
    LABEL_ROBOT,

    LABEL_RIGHT_WHEEL,
    LABEL_LEFT_WHEEL,

    LABEL_PETROL,
    LABEL_DIESEL,
    LABEL_HYBRID,

    LABEL_FWD,
    LABEL_RWD,
    LABEL_FULL_WD,

    NO_DATA,

    // CarOptions

    // ERRORS

    ERROR_CALL,
    ERROR_EMPTY_PASSWORD,
    ERROR_INCORRECT_PASSWORD,
    ERROR_FAILED_CHANGE_PASSWORD,
    ERROR_PASSWORDS_DONT_MATCH,
    ERROR_NO_IMAGES,
    ERROR_FIELD_AND_OPTIONS_NOT_FILLED_IN,
    ERROR_TO_CREATE_AD,
    ERROR_TO_SEND_VERIF_CODE,
    ERROR_TO_SEND_LINK_TO_RESET_PASSWORD,
    ERROR_REGISTRATION_FAILED,
    ERROR_SEND_MESSAGE,
    ERROR_OPEN_CHAT,
    ERROR_LISTEN_CHATS,
    ERROR_SHOW_USER_DATA,
    ERROR_GET_USER,
    ERROR_TIMEOUT_ERROR,
    ERROR_LOGIN,
    ERROR_UPDATE_USER_FIELDS,

    // ERRORS

    // INFO

    INFO_PASSWORD_IS_CHANGED,
    INFO_VERIF_CODE_SENT,
    INFO_LINK_TO_RESET_PASSWORD_SENT,
    INFO_REGISTRATION_SUCCESS,
    INFO_UPDATE_USER_FIELDS_SUCCESS,
    INFO_AD_CREATED

    // INFO
}