package com.example.autohub.presentation.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Представляет размеры с различными уровнями отступов.
 *
 * Используется для определения отступов (padding, size и т.п.) в различных компонентах
 * пользовательского интерфейса.
 */
data class Dimensions(
    val emptySize: Dp,
    val ultraSmall: Dp,
    val microSmall: Dp,
    val extraSmall: Dp,
    val small: Dp,
    val smallMedium: Dp,
    val medium: Dp,
    val extraMedium: Dp,
    val checkboxSize: Dp,
    val ultraMedium: Dp,
    val large: Dp,
    val extraLarge: Dp,
    val ultraLargeMedium: Dp,
    val extraLargeMedium: Dp,
    val ultraLarge: Dp,
    val maxSizeScreen: Dp = 540.dp,
    val imageAspectRatio: Float,
    val fullWeight: Float,
    val inputFieldWeight: Float,
    val buttonFillHalfWidth: Float,
    val carAdElevation: Dp,
    val carAdsMainAdCardImageSize: Dp,
    val bottomIconSize: Dp,
    val profileImageSize: Dp,
    val smallBorderSize: Dp,
    val mediumBorderSize: Dp,
    val ultraSmallBorderSize: Dp,
    val adDataColumnWeight: Float,
    val gridAdsElevation: Dp,
    val iconImage: Dp,
    val textFieldWidth: Float,
    val buttonWidth: Float,
    val circleStatusSize: Dp,
    val messageMaxSize: Float,
    val messageElevation: Dp,
    val messageReadCircleSize: Dp,
    val chatUserImage: Dp,
    val unreadMessagesCircle: Dp,
    val chatInfoWidth: Float,
    val chattingProfileImageSize: Dp,
    val adProfileImageSize: Dp,
    val maxAdImageWidth: Dp,
    val carAdCardImageSize: Dp,
)

/**
 * Набор дефолтных значений
 */
val defaultDimensions = Dimensions(
    emptySize = 0.dp,
    ultraSmall = 4.dp,
    microSmall = 6.dp,
    extraSmall = 8.dp,
    small = 12.dp,
    smallMedium = 14.dp,
    medium = 16.dp,
    extraMedium = 20.dp,
    checkboxSize = 20.dp,
    ultraMedium = 24.dp,
    large = 32.dp,
    extraLarge = 36.dp,
    ultraLarge = 40.dp,
    ultraLargeMedium = 40.dp,
    extraLargeMedium = 48.dp,
    imageAspectRatio = 4/3f,
    fullWeight = 1f,
    inputFieldWeight = 3f,
    buttonFillHalfWidth = 0.5f,
    carAdElevation = 4.dp,
    carAdsMainAdCardImageSize = 150.dp,
    bottomIconSize = 30.dp,
    profileImageSize = 100.dp,
    chattingProfileImageSize = 70.dp,
    smallBorderSize = 2.dp,
    mediumBorderSize = 4.dp,
    ultraSmallBorderSize = 1.dp,
    adDataColumnWeight = 3f,
    gridAdsElevation = 0.5.dp,
    iconImage = 30.dp,
    textFieldWidth = 0.8f,
    buttonWidth = 0.7f,
    circleStatusSize = 4.dp,
    messageMaxSize = 0.7f,
    messageElevation = 2.dp,
    messageReadCircleSize = 7.dp,
    chatUserImage = 50.dp,
    unreadMessagesCircle = 30.dp,
    chatInfoWidth = 4f,
    adProfileImageSize = 70.dp,
    maxAdImageWidth = 400.dp,
    carAdCardImageSize = 300.dp,
)